### ISSUE TITLE
Question on compiling for GD32 Voxelab Aquila.

### ISSUE THREAD

**Issue by bstork0807** [classicrocker883/MRiscoCProUI#19] opened 2023-02-12 19:18 UTC
Not sure this is the correct place for this but I believe I have tried all options when compiling. I have a Voxelab Aquila G32 and I can take you pre-compiled which works great. I just wanted to tweak some stuff and set it in the firmware so I wouldnt have to fix all the settings after reflashing.. What is your recommendation to do this.. I have VScode setup ready to go..

**Comment by classicrocker883** [comment] 2023-02-15 02:24
hey @bstork0807, yes you can use VS code to compile if you know how to do all that you should be good to go.

However some things to take note. The Configuration.h and Configuration_adv.h files directly in the Marlin folder should be replaced with the ones under Configurations. you'll see MM and UBL or default.

Then you may have to change the default_env in the platformio.ini file to your correct chip. just be aware that some tweaks (enabling options) cause the file to be too big and you won't be able to flash it properly.

I'm curious as to what sort of things you'd like changed?

**Comment by bstork0807** [comment] 2023-02-15 12:53
I have most of what you said... Copied the Configuration.h and Configuration_adv.h files for ubl..  When it comes to the platformio file I have the GD32 chip and have used your GD32-UBL_ProUI_BLT.bin and it works great.. Any info on how you set the platfirmio.ini and what you pick when you autobuild would be greatly appreciated.   As far as what i want to change, at this point want to make a bin file that will configure all my settings so I dont have to go in after the fact. For example extruder esteps.. 

I don't know if it is possible, could you share your config files along with platformio that I could use to try and compile for the GD32-UBL_ProUI_BLT.bin

**Comment by classicrocker883** [comment] 2023-02-17 04:18
`STM32F103RC_voxelab_maple_GD32` this is what i put after the `default_envs=` in platformio.ini
personally i dont use the Marlin Auto Build extension. if you want to change the settings with your own just go into the Configuration.h file do ctrl-f and type whatever you'd like to change. my config files are saved in the configurations folder under Andrew427. however that is specifically for the 427 board which if you want the UBL with ProUI, i suggest going into those specific Config files, copy and paste into the main marlin folder, the ones youre looking for have _Pro_ at the end, so copy those but dont forget to remove "_Pro_". because for the Aquila Boards, they can only hold upto 256k memory, not 512k like the 427. that is why some options or features aren't enabled for the _UBL_ProUI_.

so if youre looking to reenable some things, you would have to disable some other things, or have some features removed from the UI, if that makes any sense. are u good? anything else u need?

**Comment by bstork0807** [comment] 2023-02-17 14:44
OK seems to be getting closer and thank you for all your help so far.. For the board I have put in BOARD_VOXELAB_AQUILA and in the platformio I have tried both STM32F103RC_voxelab_maple_GD32 and GD32F103RC_voxelab which resulted in the following.. thinking maybe a config with in vscode.. any ideas would be appreciated.
![Screenshot 2023-02-17 094203](https://user-images.githubusercontent.com/57011584/219685869-3e031efb-0045-42af-a89d-6185ede3c28d.jpg)

**Comment by bstork0807** [comment] 2023-02-17 15:51
Ignore the previous message.. it turns out the aquila256k.ld script is named aquila_256k.ld in the directory for some reason.. but now that I got past that point I noticed the following error in the output section. I am thinking it has to do with removing the PRO.. how do I do that?
![outputScreenshot 2023-02-17 104434](https://user-images.githubusercontent.com/57011584/219700117-4eea63f3-b81e-452b-b88d-1bb81e885f10.jpg)

I am now getting this at the end of the compile with the maple

![Screenshot 2023-02-17 105121](https://user-images.githubusercontent.com/57011584/219701491-6611de25-2d43-4485-9dae-8a0723f6bfc4.jpg)

**Comment by bstork0807** [comment] 2023-02-17 16:55
Getting closer, I used the Andrew Build and now it is saying not enough space.. What did you disable in order for it to fit for the GD32.

**Comment by classicrocker883** [comment] 2023-02-18 21:17
i had disabled several things, not exactly sure which ones but like the nozzle clean, if you `Select to Compare` the files, the same configuration or configuration_adv files, and `Compare with Selected` you should be able to see the differences. the thing about the aquila is yeah it wont hold more than 89% of the 256k. i remember seeing that same or similar error, but im not remembering what the cause or fix is.

can you attach your configuration.h and configuration_adv.h files so i can look? or was there any other file you changed (*besides the platformio.ini*)

**Comment by classicrocker883** [comment] 2023-02-18 21:34
ok i recreated the issue by commenting out `#define ProUIex 1` in configuration.h line 3191.

that should be enabled. that is the ProUI, if it is disabled, you will have to also disable `HAS_GCODE_PREVIEW`

**Comment by bstork0807** [comment] 2023-02-19 01:12
Attached are the configurations and platformio
[configs.zip](https://github.com/classicrocker883/MriscocProUI/files/10775485/configs.zip)

**Comment by Lord-Memester** [comment] 2023-02-19 04:18
I was so close to being done. Then I got this:
![image_2023-02-18_221753265](https://user-images.githubusercontent.com/71044282/219921929-02afb361-1086-4360-8a4c-f8afe2ef8ceb.png)
Some sort of ROM overflow. I truly don't know what to do about that.

**Comment by Lord-Memester** [comment] 2023-02-19 05:38
I was successfully able to build it! I cloned the repository, so I'll upload my works as a fork.
![image_2023-02-18_233839156](https://user-images.githubusercontent.com/71044282/219928809-59ec46a8-a564-48c2-a91e-f9da8ec10e26.png)

**Comment by classicrocker883** [comment] 2023-02-19 08:24
the overflow means it is too big, there are somethings you would have to disable, start with the least used like the options under where `ProUIex` is: the lockscreen, esdiag, ect...

there are a couple other ways to save space like commenting out some things in the *dwin.cpp* file under **src/lcd/e3v2/proui** i know that is pretty vague if you dont know much about code, but basically how the UI user interface looks and how the menus are constructed are coded in that specific file. such as being able to view the PID plot graph while printing, that can be commented out to save space, also it has two different ways to view the Mesh grid, you can save space by having just one.

since you have almost 86% meaning u can squeeze 3% more space, there are some things you can go back to enable, but honestly its more trial and error figuring out how much byte size youre adding or taking away. 8600 bytes over can be one or two things, or several small things. so its good to start with disabling the larger ones first, because you can keep the smaller type options, you know the more options youre able to keep the better, so you at least _have_ them.

**Comment by Lord-Memester** [comment] 2023-02-19 14:58
Sorry, but what lines would those be in `dwin.cpp`? Having some trouble finding them.

Edit: Is it lines `267-348`?

**Comment by bstork0807** [comment] 2023-02-20 23:33
Good evening. Just curious if you were able to compare your files to mine. If you could share your config files that you used to build the gd32 proui bin files I would have no issue building it myself and comparing. Thank you again.

**Comment by Lord-Memester** [comment] 2023-02-21 06:24
> Good evening. Just curious if you were able to compare your files to mine. If you could share your config files that you used to build the gd32 proui bin files I would have no issue building it myself and comparing. Thank you again.

Do you mean me or @classicrocker883 ? I'll take a look if you'd like.

**Comment by bstork0807** [comment] 2023-02-21 11:15
Good evening. Just curious if you were able to compare your files to mine. If you could share your config files that you used to build the gd32 proui bin files I would have no issue building it myself and comparing. Thank you again.

**Comment by bstork0807** [comment] 2023-02-21 11:17
I was asking classicrocker883 but looking for help on what was commented out to save the space.

**Comment by classicrocker883** [comment] 2023-02-21 20:20
> Sorry, but what lines would those be in `dwin.cpp`? Having some trouble finding them.
> 
> Edit: Is it lines `267-348`?

I was thinking more like lines `1626-1664`
*//Temperature (PID Tuning Graph) Plot During Printing*

you'd have to comment out the two menu options under `draw_tune_menu`
**PID Plot bed+nozzle**

also if you want just one mesh grid viewer, if u want the newer one I think all u have to do is comment out 'MESH_VIEWER' - - that may not be the exact **#define** but I'll have to look for it.

edit: it's `USE_UBL_VIEWER`, not sure which folder it's in but if you comment it out then you'll just have the one new mesh viewer. which should save space.

**Comment by bstork0807** [comment] 2023-02-21 21:00
Andrew. When you compiled the gd32 version of the bin files did you reduce to 256k or 512k?  I heard even though the gd32rct version has 256k it can handle the 512k software

**Comment by classicrocker883** [comment] 2023-02-22 09:38
@bstork0807 yes it had to be reduced to 256k, its true these chips **should be able** to handle 512k as the specs say, however that is not the case when flashing the firmware. for whatever reason, voxelab has probably set a limit on these chips and they cant be compiled to be more than 89% of 256k. you can see for yourself and  in platformio.ini set `default_envs=` it to `STM32F103RE_voxelab_maple_GD32` just by changing the C to an E. the reason why I had put GD32 or N32 at the end was so its easier when compiling using the WORKFLOWS actions.

that was initially a problem for me - getting the firmware to flash properly. I didn't realize it had to do with size of the file until after lots of trial and error.

but if youre able to somehow get more memory to work with these chips that would be great. it may have something to do with the bootloader, I think it was something voxelab hard coded in their chips because if the firmware file is too big it could brick the chip, so their thinking is its a safeguard. for that, u may need special STM32 CubeMX software or similar.

anyway, ill take a look at the files if youre still having trouble compiling.

**Comment by Lord-Memester** [comment] 2023-02-22 16:26
> @bstork0807 yes it had to be reduced to 256k, its true these chips **should be able** to handle 512k as the specs say, however that is not the case when flashing the firmware. for whatever reason, voxelab has probably set a limit on these chips and they cant be compiled to be more than 89% of 256k. you can see for yourself and  in platformio.ini set `default_envs=` it to `STM32F103RE_voxelab_maple_GD32` just by changing the C to an E. the reason why I had put GD32 or N32 at the end was so its easier when compiling using the WORKFLOWS actions.
> 
> that was initially a problem for me - getting the firmware to flash properly. I didn't realize it had to do with size of the file until after lots of trial and error.
> 
> but if youre able to somehow get more memory to work with these chips that would be great. it may have something to do with the bootloader, I think it was something voxelab hard coded in their chips because if the firmware file is too big it could brick the chip, so their thinking is its a safeguard. for that, u may need special STM32 CubeMX software or similar.
> 
> anyway, ill take a look at the files if youre still having trouble compiling.

Should we attempt to contact Voxelab support about this? At least in the past, they've been responsive enough that they might be able to offer an explanation for this.

**Comment by bstork0807** [comment] 2023-02-22 18:32
I havent tested as of yet but was able to compile using the non-maple library because it takes up less space.. what is the reason the maple library is used?? Below is the successful compile.
![image](https://user-images.githubusercontent.com/57011584/220724049-c562d39e-bc94-49da-ad15-fd52cd0f5e99.png)

**Comment by classicrocker883** [comment] 2023-02-23 08:30
> I havent tested as of yet but was able to compile using the non-maple library because it takes up less space.. what is the reason the maple library is used?? Below is the successful compile. ![image](https://user-images.githubusercontent.com/57011584/220724049-c562d39e-bc94-49da-ad15-fd52cd0f5e99.png)

yeah it does use less, because it doesn't use as many libraries. I'm honestly not exactly sure the differences, all I know is the Aquila boards won't flash with non-Maple firmware.

did you try flashing it? and how did it go?

because in my tests I haven't been able to get it to flash properly. so I stuck with the Maple for `default_envs`

**Comment by classicrocker883** [comment] 2023-02-23 08:37
> 
> Should we attempt to contact Voxelab support about this? At least in the past, they've been responsive enough that they might be able to offer an explanation for this.

you can try and ask them, you might get an answer. but I doubt it will be one to unlock the chips potential. even so, it may not be worth the hassle. sure go ahead and ask why they limited the chips memory or ram or rom whatever it was. or it could be something with the chips manufacturer. while you're at it, ask why can only Maple environments work for the chip, and if there is a way to use non-Maple. if that makes sense.

I think a good source of knowledge would be Mr Alex alexqzd himself. he was in contact with Voxelab for a while and was able to get all the chips working. I'm sure he would know the answers, but I haven't heard or seen a lot of him around lately...

**Comment by bstork0807** [comment] 2023-02-23 14:05
Well figured it out.. looks like it was my mistake the entire time.. The files have not been put in the released folder and that has been where I have been pulling the directories from.. I was able to compile successfully using the Pro files below. I just need to load them on the printer and had a print job running this morning. I will let everyone know how it works. Looks like the following had to be disabled: 
//#define G26_MESH_VALIDATION
//#define EEPROM_CHITCHAT 
//#define NOZZLE_CLEAN_FEATURE
//#define HAS_ESDIAG 1
//#define SET_PROGRESS_MANUALLY 
//#define POWER_LOSS_RECOVERY
![image](https://user-images.githubusercontent.com/57011584/220928810-881dc852-c299-449d-8162-a16eeecc1141.png)

**Comment by Lord-Memester** [comment] 2023-02-23 17:15
I actually haven't had much luck compiling for ProUI. If that's what
you're going with, please let me know how it goes.

**Comment by bstork0807** [comment] 2023-02-23 17:20
So what issues did you have compiling.. just so I know what I am looking for..

**Comment by Lord-Memester** [comment] 2023-02-23 21:20
[image: image.png]
Size overflow.

**Comment by Lord-Memester** [comment] 2023-02-23 21:21
Rom overflow.
![image](https://user-images.githubusercontent.com/71044282/221033042-08e7ecd6-9890-4c7e-9d2d-1f078bbcb5ae.png)

**Comment by bstork0807** [comment] 2023-02-23 21:28
did you copy the configuration pro.h and configuration_adv pro.h and rename them to configuration.h and configuration_adv.h?

**Comment by Lord-Memester** [comment] 2023-02-23 21:29
No, I wanted them to be custom, so I'm just messing about with the normal config files. I suppose comparing the two couldn't hurt.

**Comment by bstork0807** [comment] 2023-02-23 21:33
yes.. i was trying to customize as well but if you use those files as starting points it should work for you

**Comment by Lord-Memester** [comment] 2023-02-26 06:22
@classicrocker883 I just compiled the firmware with a non-maple build and the output was a file less than 201 KB! I haven't tested it yet, but the file size at least seems promising. I'll edit this comment to let you know how it goes.

It did not work. Not sure why, but I'm going to recompile it with the maple build and use that to see what (if any) difference there is.

So, the difference is that the maple build proceeded past the upload screen. The non-maple build did not, but it appeared to upload _something_.

I haven't compared the two files bit-to-bit or byte-to-byte, but it might be interesting to see exactly what changes.

**Comment by bstork0807** [comment] 2023-02-26 14:19
I was able to do the same just haven't had time to load on the printer as my son is printing parts for school robotics competition.

**Comment by Lord-Memester** [comment] 2023-02-26 20:27
> I was able to do the same just haven't had time to load on the printer as my son is printing parts for school robotics competition.

Wait, that wouldn't happen to be a FIRST Robotics competition, would it?

**Comment by bstork0807** [comment] 2023-02-26 20:30
It is the FRC 2023. Have a practice comp in about a week.

**Comment by Lord-Memester** [comment] 2023-02-26 20:31
Ooh, what team number? Depending on where you live, we might end up facing off!
(Although, if you'd rather not share it publicly for privacy reasons, I understand.)

**Comment by bstork0807** [comment] 2023-02-26 20:54
We are going to SBPLI 1 @Hosfstra and then we will be in Pittsburgh PA

We did go to Houston last year. 

Where are you from?

**Comment by Lord-Memester** [comment] 2023-02-26 21:16
Far from there. I'm in the Midwest, and it's unlikely my team will make it far enough along in the competitions to meet. Oh well.

**Comment by Lord-Memester** [comment] 2023-02-26 21:21
> 3171 Westhampton Beach. Long Island NY. We are going to SBPLI 1 @Hosfstra and then we will be in Pittsburgh PA
> 
> We did go to Houston last year.
> 
> Where are you from?

You may want to keep in mind that anyone on the internet can view this information, in case you didn't already know.

**Comment by bstork0807** [comment] 2023-03-04 03:06
Did you try and load the new compile?

**Comment by Lord-Memester** [comment] 2023-03-04 03:09
Depending who you're asking, I've since edited my comment. I haven't tried loading the new version yet as I've been calibrating input shaping.

**Comment by bstork0807** [comment] 2023-03-04 13:26
I was asking you,sorry didn't see that you modified. I compiled with maple and it is working great. I am working on tweaking linear advance.

**Comment by Lord-Memester** [comment] 2023-03-04 22:24
> I am working on tweaking linear advance.

Oh, do let me know how it goes! I'm wary of going to more extreme measures to figure out the issue, so if it works for you on your (mostly stock) setup, I'd love to know.

**Comment by classicrocker883** [comment] 2023-03-04 23:19
> I was asking you,sorry didn't see that you modified. I compiled with maple and it is working great. I am working on tweaking linear advance.

for linear advance, I'd like you to know that in **src/module/planner.h**, you will see line ~200
`typedef struct block_t`

however in the MarlinFirmware files, it is `typedef struct PlannerBlock`.

it was at one time changed from block_t to PlannerBlock, but would not compile so I changed it back to block_t. now I don't know if it compiles correctly using the MarlinFirmware source code files, if it is deliberate or a mistake.

that is one of the only changes I had made regarding linear advance, so maybe this is something to look into.

**Comment by Lord-Memester** [comment] 2023-03-04 23:20
Interesting. This is the new marlin you recently combined with the previous version, right? I may just go ahead and pull from source.

**Comment by classicrocker883** [comment] 2023-03-04 23:33
I combined with the new Marlin under the branch `2023-Feb`, haven't tested but it compiled fine. (it has the struct block_t - not PlannerBlock)

**Comment by Lord-Memester** [comment] 2023-03-04 23:33
> I combined with the new Marlin under the branch `2023-Feb`, haven't tested but it compiled fine. (it has the struct block_t - not PlannerBlock)

Let me know when you've tested it, please!

**Comment by classicrocker883** [comment] 2023-03-07 00:32
@Lord-Memester are you able to compile your own firmware? because I saw in the newest update to Marlin, I mean the very newest - newer than like a week ago since I last looked through it - there were specific changes to linear advance and to the extruder in the code. I just (on Mar-06) updated the 2023-Feb branch yet again and it compiles fine. 

I'm sure this would fix something! I'll post some .bin files probably sometime today. care to share what you use so I'll have that ready first? like the chip/board and UBL, manual mesh, 5x5, 7x7, ect...

**Comment by Lord-Memester** [comment] 2023-03-07 04:05
> @Lord-Memester are you able to compile your own firmware? because I saw in the newest update to Marlin, I mean the very newest - newer than like a week ago since I last looked through it - there were specific changes to linear advance and to the extruder in the code. I just (on Mar-06) updated the 2023-Feb branch yet again and it compiles fine.
> 
> I'm sure this would fix something! I'll post some .bin files probably sometime today. care to share what you use so I'll have that ready first? like the chip/board and UBL, manual mesh, 5x5, 7x7, ect...

@classicrocker883 
I can build my own firmware, but I haven't gotten around to it with the new version. I've been swamped with work, and I won't have much of a break until next week. For now, [you can look through my fork](https://github.com/Lord-Memester/MriscocProUI), though I haven't incorporated the very latest changes into my build. I'll attempt to do that sometime today or tomorrow, but I can't guarantee anything.

**Comment by Lord-Memester** [comment] 2023-03-07 22:50
![image](https://user-images.githubusercontent.com/71044282/223571874-5049e41a-5db5-45f9-8719-8aa690f5278d.png)
Recent compilation error. I don't want to run ProUI, and this seems to be causing issues.

**Comment by classicrocker883** [comment] 2023-03-08 05:05
@Lord-Memester I since fixed this, it should be working fine. Also i posted a couple quick pre releases for testing if you want to check it out.

**Comment by Lord-Memester** [comment] 2023-03-08 05:18
> @Lord-Memester I since fixed this, it should be working fine. Also i posted a couple quick pre releases for testing if you want to check it out.

I'll see if I have time to try the prereleases. If you're willing, would you specify what files you changed?

**Comment by SrgWhoopsie** [comment] 2023-03-08 05:42
i know im using a different board but i noticed there was not an answer for this above from a couple weeks ago, and i cannot get get the build env do its thing lol
![marlin vscode error](https://user-images.githubusercontent.com/107329142/223628567-1e81754e-23d8-4384-9b43-c5a77fd81d1e.png)
what am i doing wrong?

**Comment by Lord-Memester** [comment] 2023-03-08 21:26
> i know im using a different board but i noticed there was not an answer for this above from a couple weeks ago, and i cannot get get the build env do its thing lol ![marlin vscode error](https://user-images.githubusercontent.com/107329142/223628567-1e81754e-23d8-4384-9b43-c5a77fd81d1e.png) what am i doing wrong?

Well, I have to say, if you're using the wrong board, you might want to start there. Try enabling verbose mode and then paste the output in here, or try making an issue in the main Marlin firmware repository.

**Comment by SrgWhoopsie** [comment] 2023-03-08 23:11
For what its worth, im not using the wrong board..... i ditched the stock board for the e3 mini, hence why its changed. 
Considering this is in the platformio.ini file i assumed there would be no issues. ![Screenshot_20230309_095739.jpg](https://user-images.githubusercontent.com/107329142/223870616-4a5b570f-920c-4731-8463-d41973ad7a65.jpg)

this issue happens as soon as i open the folder in vscode, doesnt matter if i change board or leave it on the STM32F103RC_creality_maple. 
This is why im confused, as i dont get this issue when opening any other source code folder for marlin ive downloaded from git only the proui stuff.

Mriscoc reference ![IMG_20230309_100933.jpg](https://user-images.githubusercontent.com/107329142/223873253-dfcc8f5d-ce78-4ce7-8a03-e5255f2634f9.jpg)

Classicrocker reference 
![IMG_20230309_101100.jpg](https://user-images.githubusercontent.com/107329142/223873382-25beae8a-0fa0-4df8-8129-b584b750a645.jpg)



Or have i understood this wrong and mriscoc or classicrockers firmware connot be complied for anything other that a STM32F series chipsets?

Also sorry for the shotty photo, cannot screen grab ATM as im at work.

**Comment by Lord-Memester** [comment] 2023-03-09 01:28
I'm realizing I may not be the best person to answer, and we should probably wait for @classicrocker883 to chime in. However, I would like to suggest that you manually type the command to build the firmware in the terminal. I don't remember it off the top of my head, but you can specify which board you want it to build for even if the platformio.ini says something else. Maybe give that a try?

**Comment by Lord-Memester** [comment] 2023-03-10 03:12
> @Lord-Memester I since fixed this, it should be working fine. Also I posted a couple quick pre releases for testing if you want to check it out.

@classicrocker883 I have since compiled it with Linear Advance under the latest branch, and encountered the same issue. With my very limited time recently, it might be best that you test them yourself, but I can compile it with the debug flag enabled for LA and let you know what I see (if anything).

I saw in the new firmware that it mentioned low e-jerk, though, and am including my [EEPROM settings](https://github.com/classicrocker883/MriscocProUI/files/10938179/eeprom_backup-20230309-212010.txt) for reference purposes. At this point, @bstork0807 may wish to chime in and provide their own EEPROM settings specific to linear advance (like e-jerk, e-accell, e-max speed, etc.).

**Comment by bstork0807** [comment] 2023-03-10 17:36
I will check this weekend and post. Been crazy busy family and work life.

**Comment by classicrocker883** [comment] 2023-03-11 03:18
@SrgWhoopsie have you changed the Author's name? that error can come up if you change it from `STRING_CONFIG_H_AUTHOR "Miguel A. Risco-Castillo (MRiscoC)" `

also I haven't yet updated the BTT SKR Mini E3 config files if you are using those. ill get to it and probably by the time you see this youll see an update (but I am primarily working on the `Mriscoc-Feb` branch so youll see those changes there).

you must have that board under the `MOTHERBOARD` in Configuration.h, there are differences between each board and it has to match to the `default_envs` in platformio.ini, as far as i know there are a couple different types of chips for the SKR mini E3, so be sure that chip matches the `default_envs`.

**Comment by classicrocker883** [comment] 2023-03-11 06:01
@SrgWhoopsie are you trying to compile using `STM32F401RC_btt`?
you must go into **ini/stm32-common.ini** and comment out using # these two lines line that have "proui" in them
![Screenshot 2023-03-11 005903](https://user-images.githubusercontent.com/18502096/224467927-e34fe706-2937-48f3-ac24-b0454a2fbedf.png)

i updated the config files for the SKR mini, so be sure to look them over.

also, if youre using the RC chip type, you may have to disable some features because some options will not fit. go for the least used like `NOZZLE_CLEAN`

**Comment by SrgWhoopsie** [comment] 2023-03-11 22:34
@classicrocker883 so when i first tried compiling i did change author, but since i have left everything as pulled from git, im just tried opening up your feb branch in vscode via github desktop, (i just cloned it to my pc inside git desktop) so its exact as you branch is, i get the failure as soon as vscode opens, then if i copy the config files over from the config folder, and try to compile i still get the same issue, 

 
![marlin vscode error](https://user-images.githubusercontent.com/107329142/224513700-5f4c14f9-5f5e-4ac8-a2f7-ddd1c03141b2.png)
i added a screen grab with verbose 

to clarify i am using the STM32G0B1RE env as i have the v3, tho i cannot remember if the board has a STM32G0B0RET6 or a STM32G0B1RET6
i forgot to take a photo before installing lol defs a G0 .

ive compiled the latest marlin bugfix for the printer and its running that no issues for the time being, just using DWIN_MARLINUI_PORTRAIT tho i forgot to publish my changes i made on my work laptop to my fork lol. tho a quick make of firmware platform io says ive got a good meat of mem left 
![memory usage](https://user-images.githubusercontent.com/107329142/224513692-4edc44e9-c9db-4efc-9d20-df411e13c15a.png)


so putting the hash on the proui in the stm32 common fixed it, but does this mean that its not going to load the dependencies for proui when i compile? seems its a dependencies issue with pio from this terminal output  
![pio_clean_no-proui](https://user-images.githubusercontent.com/107329142/224514301-a35ece05-0e8c-4b41-a9ec-3f45fee95e0d.png)

if i use the configuration files in the configuration folder for the BTT-SKR_Mini_E3_V3 i get a env_validate error
![from_config_folder](https://user-images.githubusercontent.com/107329142/224514407-9ffe1ce0-d460-455d-8514-f239e45199b7.png)

**Comment by bstork0807** [comment] 2023-03-12 16:35
Attached are my settings.. i only played around with acceleration
![image](https://user-images.githubusercontent.com/57011584/224558679-6fc7d1f1-0409-4c02-9232-fcb9768bd06a.png)

**Comment by Lord-Memester** [comment] 2023-03-12 20:35
> Attached are my settings.. i only played around with acceleration ![image](https://user-images.githubusercontent.com/57011584/224558679-6fc7d1f1-0409-4c02-9232-fcb9768bd06a.png)

Interesting. Are you sure you never changed E-jerk? The E-jerk default value in my config is 5, located somewhere in line 1,290-1,305. I don't believe I've edited it.

```c++
/**
 * Default Jerk limits (mm/s)
 * Override with M205 X Y Z . . . E
 *
 * "Jerk" specifies the minimum speed change that requires acceleration.
 * When changing speed and direction, if the difference is less than the
 * value set here, it may happen instantaneously.
 */
#define CLASSIC_JERK  // Ender Configs
#if ENABLED(CLASSIC_JERK)
  #define DEFAULT_XJERK 10.0  // Ender Configs
  #define DEFAULT_YJERK 10.0  // Ender Configs
  #define DEFAULT_ZJERK  0.3  // Ender Configs
  //#define DEFAULT_IJERK  0.3
  //#define DEFAULT_JJERK  0.3
  //#define DEFAULT_KJERK  0.3
  //#define DEFAULT_UJERK  0.3
  //#define DEFAULT_VJERK  0.3
  //#define DEFAULT_WJERK  0.3

  //#define TRAVEL_EXTRA_XYJERK 0.0     // Additional jerk allowance for all travel moves

  //#define LIMITED_JERK_EDITING        // Limit edit via M205 or LCD to DEFAULT_aJERK * 2  // Ender Configs
  #if ENABLED(LIMITED_JERK_EDITING)
    #define MAX_JERK_EDIT_VALUES { 20, 20, 1, 20 } // ...or, set your own edit limits  // MRiscoC allows higher limits
  #endif
#endif

#define DEFAULT_EJERK    5.0  // May be used by Linear Advance  // Ender Configs```

**Comment by classicrocker883** [comment] 2023-03-12 23:14
here is the thing about proui, it's only for the "`DWIN_LCD_PROUI`" (ender 3 v2 and Voxelab Aquila full color LCD) the ProUI can't work on the `CR10_STOCKDISPLAY`. you can use that screen on the skr mini e3, but it requires you to modify the wires (I believe u need to swap two wires) and editing in the firmware.

as for the env_validate error I may have made a mistake editing those files and accidentally uploaded them as I was troubleshooting the issue. because when I compiled to see if everything was good, it was successful.

so if you can before I get a chance, you could copy over those files from the Marlin bugfix and replace them in the Mriscoc-Feb branch. the files being pins/stm32g0/pins_BTT-SKR_Mini_E3_V3_0.h and env_validate.h. if you compare the files they may be different because I copied over one into the other so I could test something. and I think I forgot to undo that.

**Comment by classicrocker883** [comment] 2023-03-12 23:27
@SrgWhoopsie 

!! the file isn't even in there no wonder. [here is the correct file](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/pins/stm32g0/env_validate.h) you need to paste in the **pins/stm32g0** folder


yeah those # need to be put infront of the lines with proui in that file or you get that error doing a clean. if you get any output error it's fine, maybe Mriscoc will have it fixed in the next update. so what I do is comment those out, do a clean, restart VS code so it loads the c_cpp_properties file so it automatically updates whatever you enable or disable, and u can remove the # before compiling. and again, proui is only needed when using the color 4.3" LCD.

**Comment by classicrocker883** [comment] 2023-03-13 09:05
just published a new branch `2023-March` i was able to make a successful compile, the update just came out so i haven't been able to do any testing yet.

**Comment by bstork0807** [comment] 2023-03-13 17:40
I do have ejerk set to 5.. u can check my code below
https://github.com/bstork0807/MriscocProUI-For-Bills-Aquila-

**Comment by classicrocker883** [comment] 2023-03-14 03:24
> I do have ejerk set to 5.. u can check my code below https://github.com/bstork0807/MriscocProUI-For-Bills-Aquila-

there is a setting in `LIN_ADVANCE` in the config_adv.h file that says `ALLOW_LOW_EJERK` which allows less than 10 recommended for direct drive. I wish I knew more about this in context, as to what setting would be better with Bowden vs direct drive, and with or without linear advance. so I just am guessing that perhaps higher EJERK will be better with linear advance? i dont know, i haven't gone so much into testing it all, especially when they keep updating everything.

another thing is Junction Deviation. that can be enabled when `CLASSIC_JERK` is disabled. also, `EXPERIMENTAL_SCURVE` has been removed from `LIN_ADVANCE` options, again, i wish i knew the whole process of why it was there and why it was removed, and benefits or disadvantages with `S_CURVE_ACCELERATION` with Linear Advance. there should be a whole write up about this, like a change log or something detailing the options and thought process of each setting and what it means when we enable/disable, and what value it should be set at.

**Comment by Lord-Memester** [comment] 2023-03-25 00:59
>again, i wish i knew the whole process of why it was there and why it was removed, and benefits or disadvantages with `S_CURVE_ACCELERATION` with Linear Advance. there should be a whole write up about this, like a change log or something detailing the options and thought process of each setting and what it means when we enable/disable, and what value it should be set at.

Do you mean that you believe there is already a changelog or that you think someone should make one?

**Comment by Lord-Memester** [comment] 2023-05-07 18:25
A recent [update to marlin](https://github.com/MarlinFirmware/Marlin/issues/25069#issuecomment-1523795229) claims to have fixed the issues with LA, and after checking the repo just now, there haven't been any new issues created about Linear Advance. They closed 52 issues and merged a bunch of fixes! 

Have you merged them into this project yet? 

###### (@classicrocker883)

**Comment by classicrocker883** [comment] 2023-05-07 21:09
I merged the most recent Marlin bugfix into the repo - its **2023-May**, its the default. let me know how it goes, ill be working on getting .bin files made.

**Comment by Lord-Memester** [comment] 2023-05-09 15:16
> I merged the most recent Marlin bugfix into the repo - its **2023-May**, its the default. let me know how it goes, ill be working on getting .bin files made.

My own build seems to not die. I've only run the same tuning file twice so far, and I need to change my config back to get the bed back to normal, but I'd say I'm currently cautiously optimistic. LA doesn't seem to have any issues on my printer since the merge, but I haven't tested it sufficiently to say it works for sure.

**Comment by Lord-Memester** [comment] 2023-05-18 04:49
@classicrocker883 @bstork0807 do we want to close this issue for the time being and move to the recently created discussion instead? Seems like it's serves it's original purpose as an issue and then some.

**Comment by classicrocker883** [comment] 2023-05-20 21:25
yes thanks for the reminder

**Closed as completed by classicrocker883** 2023-05-20 21:25 UTC

**Comment by classicrocker883** [comment] 2023-05-20 21:29
also, as for a change log, I'll leave that to Mriscoc, when he posts his next update, hopefully soon, I'll make a link to that.

as for anything I change I'll write in the *Release* when new firmware .bin files are made. I'll try to mention the important things, and little changes could be seen in the commit history.
